[package]
name = "network"
version = "0.1.0"
authors = ["Amund Tenstad <github@amund.io>"]
edition = "2018"

[dependencies]
rand = "0.6.0"
libc = "0.2"
enum-display-derive = "0.1.0"
derive-new = "0.5.8"
serde = "1.0.110"
